# =============================================================================
# HelmRepository: crossplane
# =============================================================================
# Définit le dépôt Helm officiel de Crossplane
# =============================================================================

apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: crossplane
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.crossplane.io/stable

