# =============================================================================
# ServiceAccount Kubernetes pour Crossplane
# =============================================================================
# ServiceAccount pour Crossplane
# 
# ⚠️ PROJETS LAB: Pas d'annotation Workload Identity
#    On utilise Service Account Key (voir providerconfig-gcp.yaml)
# =============================================================================

apiVersion: v1
kind: ServiceAccount
metadata:
  name: crossplane
  namespace: crossplane-system
  # Annotation Workload Identity (désactivée pour projets lab)
  # annotations:
  #   iam.gke.io/gcp-service-account: crossplane-sa@PROJECT_ID.iam.gserviceaccount.com
  labels:
    app.kubernetes.io/name: crossplane
    app.kubernetes.io/part-of: crossplane

