# =============================================================================
# ServiceAccount Kubernetes pour Crossplane
# =============================================================================
# ServiceAccount avec annotation Workload Identity
# Terraform crée le binding IAM entre ce SA et le SA GCP
# =============================================================================

apiVersion: v1
kind: ServiceAccount
metadata:
  name: crossplane
  namespace: crossplane-system
  annotations:
    # Annotation Workload Identity
    # Format: PROJECT_ID.svc.id.goog[NAMESPACE/SA_NAME]
    # ⚠️ PROJECT_ID sera remplacé après terraform apply
    iam.gke.io/gcp-service-account: CROSSPLANE_SA_EMAIL_PLACEHOLDER
  labels:
    app.kubernetes.io/name: crossplane
    app.kubernetes.io/part-of: crossplane

