---
# =============================================================================
# Kustomization: Apps
# =============================================================================
# Ce fichier dit à FluxCD de réconcilier le dossier /gitops/apps
# Il dépend de l'infrastructure (ingress, cert-manager doivent être prêts)
# Sera utilisé dans la Brique 4 (Microservice)
# =============================================================================

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 5m0s            # Vérifie plus fréquemment pour les apps
  retryInterval: 1m0s
  timeout: 3m0s
  
  sourceRef:
    kind: GitRepository
    name: flux-system
  
  path: ./gitops/apps       # Chemin dans le dépôt Git
  
  prune: true
  wait: true
  
  # ⚠️ IMPORTANT: Attend que l'infrastructure soit prête
  dependsOn:
    - name: infrastructure

