---
# =============================================================================
# Kustomization: Infrastructure
# =============================================================================
# Ce fichier dit à FluxCD de réconcilier le dossier /gitops/infrastructure
# Il déploie : ingress-nginx, cert-manager, prometheus
# =============================================================================

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m0s           # Vérifie les changements toutes les 10 minutes
  retryInterval: 1m0s       # En cas d'erreur, réessaie après 1 minute
  timeout: 5m0s             # Timeout pour l'application des manifests
  
  sourceRef:
    kind: GitRepository
    name: flux-system       # Référence au GitRepository créé par bootstrap
  
  path: ./gitops/infrastructure  # Chemin dans le dépôt Git
  
  prune: true               # Supprime les ressources qui ne sont plus dans Git
  wait: true                # Attend que les ressources soient Ready

  # Health checks pour s'assurer que l'infra est prête
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: ingress-nginx-controller
      namespace: ingress-nginx

