# =============================================================================
# Exemple: Bucket GCS créé via Crossplane
# =============================================================================
# Cet exemple montre comment créer un bucket GCS depuis Kubernetes
# =============================================================================

apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  name: crossplane-demo-bucket
  namespace: default
spec:
  forProvider:
    # Configuration du bucket
    location: US-CENTRAL1
    storageClass: STANDARD
    
    # Versioning activé
    versioning:
      - enabled: true
    
    # Lifecycle: supprime les fichiers après 90 jours
    lifecycleRule:
      - action:
          - type: Delete
        condition:
          - age: 90
    
    # Labels pour le tracking
    labels:
      managed-by: crossplane
      environment: dev
      team: platform
  
  # Crossplane crée automatiquement un Secret avec les infos du bucket
  writeConnectionSecretToRef:
    name: bucket-credentials
    namespace: default

